#!/usr/bin/env python3
"""
Migrate the 10 already-scraped .md files (which use the old verbose format) into
the new .raw/ subfolder with the leaner format. Reads existing files, parses out
the metadata + transcript, and writes the new .raw.md format. Also updates
transcript-index.json to the new schema.
"""
import json
import os
import re

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(OUT_DIR, ".raw")
INDEX_FILE = os.path.join(OUT_DIR, "transcript-index.json")
PLAYLIST_NAME = "Paul"
PLAYLIST_TOTAL = 77

os.makedirs(RAW_DIR, exist_ok=True)


def parse_old_file(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    # Strip frontmatter and parse it
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        raise RuntimeError(f"No frontmatter in {path}")
    fm_block, body = m.group(1), m.group(2)
    fm = {}
    for line in fm_block.split("\n"):
        if ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip('"').strip("'")

    # Extract title (first H1)
    tm = re.search(r"^# (.+)$", body, re.MULTILINE)
    title = tm.group(1).strip() if tm else fm.get("video_title", "untitled")

    # Extract YouTube ID from URL field
    youtube_id = fm.get("youtube_id", "unknown")
    published = fm.get("published_at", "")
    duration_min = fm.get("duration_minutes", "?")

    # Extract description block (between '## Video Description' and the next '---')
    desc = ""
    dm = re.search(r"## Video Description\s*\n+(.*?)\n+---", body, re.DOTALL)
    if dm:
        desc = dm.group(1).strip()

    # Extract transcript (everything after '## Raw Transcript' header + blockquote)
    tm = re.search(r"## Raw Transcript\s*\n+>.*?\n+(.*)$", body, re.DOTALL)
    transcript = tm.group(1).strip() if tm else ""

    return {
        "title": title,
        "youtube_id": youtube_id,
        "published_at": published,
        "duration_minutes": duration_min,
        "description": desc,
        "transcript": transcript,
    }


def write_raw(item: dict, index: int) -> str:
    title = item["title"]
    youtube_id = item["youtube_id"]

    def slugify(s):
        s = s.lower()
        s = re.sub(r"[^\w\s-]", "", s)
        s = re.sub(r"\s+", "-", s).strip("-")
        return s[:80]

    slug = slugify(title)
    filename = f"{index:02d}-{slug}.raw.md"
    path = os.path.join(RAW_DIR, filename)

    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Speaker:** Dr. James Tabor")
    lines.append(f"**Source:** [YouTube](https://www.youtube.com/watch?v={youtube_id})")
    lines.append(f"**Published:** {item['published_at'][:10] if item['published_at'] else ''}")
    lines.append(f"**Duration:** {item['duration_minutes']} minutes")
    lines.append(f"**Playlist:** {PLAYLIST_NAME} (#{index} of {PLAYLIST_TOTAL})")
    lines.append("")
    lines.append("---")
    lines.append("")
    if item["description"]:
        lines.append("## Video Description (from YouTube)")
        lines.append("")
        lines.append(item["description"])
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("## Raw Transcript")
    lines.append("")
    lines.append("*Auto-generated by YouTube, scraped via Apify. Preserved as-is for reference. Punctuation/capitalization is YouTube-quality.*")
    lines.append("")
    lines.append(item["transcript"])
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return filename


def main():
    with open(INDEX_FILE, "r", encoding="utf-8") as f:
        index = json.load(f)

    new_index = {}
    for key, entry in sorted(index.items()):
        old_file = entry.get("file")
        idx = int(key)
        old_path = os.path.join(OUT_DIR, old_file)
        if not os.path.exists(old_path):
            print(f"[miss] {key} {old_file} not found, skipping")
            continue
        try:
            parsed = parse_old_file(old_path)
            new_filename = write_raw(parsed, idx)
            new_index[key] = {
                "raw_file": new_filename,
                "youtube_id": entry.get("youtube_id"),
                "title": entry.get("title"),
                "raw_status": "success",
                "duration_seconds": entry.get("duration_seconds"),
                "published_at": parsed["published_at"],
                "synthesized_status": "pending",
            }
            # Remove old file from main dir
            os.remove(old_path)
            print(f"[ok]   {key} -> .raw/{new_filename}")
        except Exception as e:
            print(f"[err]  {key} {e}")

    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(new_index, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
