#!/usr/bin/env python3
"""
Fallback YouTube transcript scraper using yt-dlp (Apify rate-limit workaround).
Downloads VTT subtitles + JSON metadata, parses to plain text, writes .raw.md
in the same format as .scrape-transcripts.py (the Apify-based scraper).

Idempotent: skips entries marked raw_status=success in transcript-index.json.
For empty/broken existing files, pass --force to overwrite.
"""
import json
import os
import re
import subprocess
import sys
import tempfile

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(OUT_DIR, ".raw")
INDEX_FILE = os.path.join(OUT_DIR, "transcript-index.json")
YTDLP_CMD = "yt-dlp"
PLAYLIST_NAME = "Paul"
PLAYLIST_TOTAL = 77

os.makedirs(RAW_DIR, exist_ok=True)


def slugify(title: str) -> str:
    s = (title or "untitled").lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s[:80] or "untitled"


def parse_vtt_to_text(vtt_path: str) -> str:
    """Convert WebVTT to a single flowing-paragraph string of plain text."""
    with open(vtt_path, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    plain_lines = []
    prev = None
    for line in lines:
        line = line.strip()
        # Skip header
        if line.startswith("WEBVTT") or line.startswith("Kind:") or line.startswith("Language:"):
            continue
        # Skip empty
        if not line:
            continue
        # Skip timestamp lines (e.g., "00:00:00.080 --> 00:00:02.550 align:start position:0%")
        if "-->" in line:
            continue
        # Strip inline timing tags <00:00:00.000>
        line = re.sub(r"<\d{2}:\d{2}:\d{2}\.\d{3}>", "", line)
        # Strip color tags <c>...</c> and similar
        line = re.sub(r"</?c[^>]*>", "", line)
        # Skip if line is now empty
        line = line.strip()
        if not line:
            continue
        # Dedupe consecutive identical lines (VTT often repeats)
        if line == prev:
            continue
        plain_lines.append(line)
        prev = line

    return " ".join(plain_lines)


def yt_dlp_metadata(youtube_url: str) -> dict:
    """Get video metadata as a dict via yt-dlp --dump-json."""
    cmd = [YTDLP_CMD, "--dump-json", "--no-warnings", "--skip-download", youtube_url]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        raise RuntimeError(f"yt-dlp metadata failed: {result.stderr[:500]}")
    return json.loads(result.stdout)


def yt_dlp_subs(youtube_url: str, out_template: str) -> str:
    """Download auto-subs (en) and return path to the .vtt file."""
    cmd = [
        YTDLP_CMD, "--write-auto-sub", "--sub-lang", "en",
        "--skip-download", "--sub-format", "vtt",
        "--no-warnings", "-o", out_template, youtube_url,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        raise RuntimeError(f"yt-dlp subs failed: {result.stderr[:500]}")
    # The VTT file path is: out_template's directory + '.en.vtt' suffix
    # When out_template is /tmp/foo.%(ext)s, the actual file is /tmp/foo.en.vtt
    base = out_template.replace(".%(ext)s", "")
    vtt_path = f"{base}.en.vtt"
    if not os.path.exists(vtt_path):
        raise RuntimeError(f"VTT not found at expected path {vtt_path}")
    return vtt_path


def write_raw(meta: dict, transcript_text: str, index: int, youtube_id: str) -> str:
    title = meta.get("title", "untitled")
    slug = slugify(title)
    filename = f"{index:02d}-{slug}.raw.md"
    path = os.path.join(RAW_DIR, filename)

    duration_sec = meta.get("duration", 0) or 0
    duration_min = round(duration_sec / 60, 1) if duration_sec else "?"
    published_at = meta.get("upload_date", "")
    if published_at and len(published_at) == 8:
        published_at = f"{published_at[:4]}-{published_at[4:6]}-{published_at[6:8]}"

    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Speaker:** Dr. James Tabor")
    lines.append(f"**Source:** [YouTube](https://www.youtube.com/watch?v={youtube_id})")
    lines.append(f"**Published:** {published_at}")
    lines.append(f"**Duration:** {duration_min} minutes")
    lines.append(f"**Playlist:** {PLAYLIST_NAME} (#{index} of {PLAYLIST_TOTAL})")
    lines.append("")
    lines.append("---")
    lines.append("")
    desc = (meta.get("description") or "").strip()
    if desc:
        lines.append("## Video Description (from YouTube)")
        lines.append("")
        lines.append(desc)
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("## Raw Transcript")
    lines.append("")
    lines.append("*Auto-generated by YouTube, downloaded via yt-dlp. Preserved as-is for reference. Punctuation/capitalization is YouTube-quality.*")
    lines.append("")
    lines.append(transcript_text)
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return filename


def cleanup_old_raw(index: int) -> None:
    """Delete any empty .raw/NN-*.raw.md file that matches this index."""
    for entry in os.listdir(RAW_DIR):
        if entry.startswith(f"{index:02d}-") and entry.endswith(".raw.md"):
            full = os.path.join(RAW_DIR, entry)
            try:
                if os.path.getsize(full) < 1000:
                    os.remove(full)
            except OSError:
                pass


def main():
    if len(sys.argv) < 2:
        print("Usage: scrape-via-ytdlp.py <videos-tsv-file> [--force]", file=sys.stderr)
        sys.exit(2)
    tsv = sys.argv[1]
    force = "--force" in sys.argv[2:]

    videos = []
    with open(tsv, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split("|", 2)
            if len(parts) < 3:
                continue
            idx, yid, title = parts
            videos.append((int(idx), yid, title))

    index = {}
    if os.path.exists(INDEX_FILE):
        with open(INDEX_FILE, "r", encoding="utf-8") as f:
            index = json.load(f)

    for idx, yid, title in videos:
        key = f"{idx:02d}"
        existing = index.get(key, {})
        # Check if a non-empty raw file already exists
        if existing.get("raw_status") == "success" and not force:
            raw_file = existing.get("raw_file", "")
            full = os.path.join(RAW_DIR, raw_file) if raw_file else None
            if full and os.path.exists(full) and os.path.getsize(full) > 1000:
                print(f"[skip] {key} already done: {raw_file}", flush=True)
                continue

        cleanup_old_raw(idx)

        url = f"https://www.youtube.com/watch?v={yid}"
        print(f"[run]  {key} {title[:70]}...", flush=True)
        try:
            meta = yt_dlp_metadata(url)
            with tempfile.TemporaryDirectory() as tmp:
                tpl = os.path.join(tmp, f"vid{idx}.%(ext)s")
                vtt = yt_dlp_subs(url, tpl)
                transcript = parse_vtt_to_text(vtt)
            filename = write_raw(meta, transcript, idx, yid)
            entry = index.get(key, {})
            entry.update({
                "raw_file": filename,
                "youtube_id": yid,
                "title": meta.get("title", title),
                "raw_status": "success",
                "duration_seconds": meta.get("duration"),
                "published_at": meta.get("upload_date"),
                "scraped_via": "yt-dlp",
            })
            entry.setdefault("synthesized_status", "pending")
            index[key] = entry
            with open(INDEX_FILE, "w", encoding="utf-8") as f:
                json.dump(index, f, indent=2, ensure_ascii=False)
            print(f"[ok]   {key} -> .raw/{filename} ({len(transcript)} chars)", flush=True)
        except Exception as e:
            print(f"[err]  {key} {e}", flush=True)
            entry = index.get(key, {})
            entry.update({
                "raw_file": None,
                "youtube_id": yid,
                "title": title,
                "raw_status": "error",
                "error": str(e),
                "scraped_via": "yt-dlp",
            })
            entry.setdefault("synthesized_status", "pending")
            index[key] = entry
            with open(INDEX_FILE, "w", encoding="utf-8") as f:
                json.dump(index, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
