#!/usr/bin/env python3
"""
Scrape YouTube transcripts via Apify CLI and save each as a raw .md file in .raw/.
After scraping, a separate human/Claude pass synthesizes each .raw file into the
Jesus Way template (Summary, Key Teachings, Scripture Citations, etc.) and writes
the polished file to the parent dr-tabor/ folder.

Input: a TSV file with lines of `index|youtube_id|title`.
Output: dr-tabor/.raw/NN-slug.raw.md per video, plus a transcript-index.json index.
"""
import json
import os
import re
import subprocess
import sys

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(OUT_DIR, ".raw")
INDEX_FILE = os.path.join(OUT_DIR, "transcript-index.json")
APIFY_CMD = r"C:\Users\rexaf\AppData\Roaming\npm\apify.cmd"
PLAYLIST_NAME = "Paul"
PLAYLIST_TOTAL = 77


def slugify(title: str) -> str:
    s = title.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s[:80]


def call_apify(youtube_url: str) -> dict:
    cmd = [
        APIFY_CMD, "call", "starvibe/youtube-video-transcript",
        "--input", json.dumps({"youtube_url": youtube_url, "language": "en", "include_transcript_text": True}),
        "--silent", "--output-dataset",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300, shell=False, encoding="utf-8", errors="replace")
    out = result.stdout or ""
    i = out.find("[")
    if i < 0:
        raise RuntimeError(f"No JSON in output for {youtube_url}: {out[:500]}\nSTDERR: {(result.stderr or '')[:500]}")
    data = json.loads(out[i:])
    if not data:
        raise RuntimeError(f"Empty dataset for {youtube_url}")
    return data[0]


def transcript_to_text(transcript_items: list) -> str:
    lines = [seg.get("text", "").strip() for seg in transcript_items if seg.get("text")]
    return " ".join(lines)


def write_raw(item: dict, index: int) -> str:
    title = item.get("title", "untitled")
    thumb = item.get("thumbnail", "")
    m = re.search(r"/vi/([\w-]+)/", thumb)
    youtube_id = m.group(1) if m else None
    if not youtube_id:
        msg = item.get("message", "")
        m = re.search(r"ID '([\w-]+)'", msg)
        youtube_id = m.group(1) if m else "unknown"

    slug = slugify(title)
    filename = f"{index:02d}-{slug}.raw.md"
    os.makedirs(RAW_DIR, exist_ok=True)
    path = os.path.join(RAW_DIR, filename)

    transcript_text = transcript_to_text(item.get("transcript", []))
    duration_sec = item.get("duration_seconds", 0)
    duration_min = round(duration_sec / 60, 1) if duration_sec else "?"

    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Speaker:** Dr. James Tabor")
    lines.append(f"**Source:** [YouTube](https://www.youtube.com/watch?v={youtube_id})")
    lines.append(f"**Published:** {item.get('published_at', '')[:10]}")
    lines.append(f"**Duration:** {duration_min} minutes")
    lines.append(f"**Playlist:** {PLAYLIST_NAME} (#{index} of {PLAYLIST_TOTAL})")
    lines.append("")
    lines.append("---")
    lines.append("")
    desc = item.get("description", "").strip()
    if desc:
        lines.append("## Video Description (from YouTube)")
        lines.append("")
        lines.append(desc)
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("## Raw Transcript")
    lines.append("")
    lines.append("*Auto-generated by YouTube, scraped via Apify. Preserved as-is for reference. Punctuation/capitalization is YouTube-quality.*")
    lines.append("")
    lines.append(transcript_text)
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return filename


def main():
    if len(sys.argv) < 2:
        print("Usage: scrape-transcripts.py <videos-tsv-file>", file=sys.stderr)
        sys.exit(2)
    tsv = sys.argv[1]
    videos = []
    with open(tsv, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split("|", 2)
            if len(parts) < 3:
                continue
            idx, yid, title = parts
            videos.append((int(idx), yid, title))

    index = {}
    if os.path.exists(INDEX_FILE):
        with open(INDEX_FILE, "r", encoding="utf-8") as f:
            index = json.load(f)

    for idx, yid, title in videos:
        key = f"{idx:02d}"
        existing = index.get(key)
        if existing and existing.get("raw_status") == "success":
            print(f"[skip] {key} raw already done: {existing.get('raw_file')}", flush=True)
            continue
        url = f"https://www.youtube.com/watch?v={yid}"
        print(f"[run]  {key} {title[:70]}...", flush=True)
        try:
            item = call_apify(url)
            filename = write_raw(item, idx)
            entry = index.get(key, {})
            entry.update({
                "raw_file": filename,
                "youtube_id": yid,
                "title": title,
                "raw_status": "success",
                "duration_seconds": item.get("duration_seconds"),
                "published_at": item.get("published_at"),
            })
            entry.setdefault("synthesized_status", "pending")
            index[key] = entry
            with open(INDEX_FILE, "w", encoding="utf-8") as f:
                json.dump(index, f, indent=2, ensure_ascii=False)
            print(f"[ok]   {key} -> .raw/{filename}", flush=True)
        except Exception as e:
            print(f"[err]  {key} {e}", flush=True)
            entry = index.get(key, {})
            entry.update({
                "raw_file": None,
                "youtube_id": yid,
                "title": title,
                "raw_status": "error",
                "error": str(e),
            })
            entry.setdefault("synthesized_status", "pending")
            index[key] = entry
            with open(INDEX_FILE, "w", encoding="utf-8") as f:
                json.dump(index, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
